import { isComposioEnabled } from "./composio-client"
import type { ActionProvider } from "./types"

type ToolkitDescriptor = {
  toolkit: string
  label: string
  description?: string
  provider?: ActionProvider
  authConfigId?: string
  scopes?: string[]
  defaultTools?: string[]
}

// Canonical, curated list of supported Composio toolkits.
// This is the source of truth for what the product supports.
const SUPPORTED_TOOLKITS: ToolkitDescriptor[] = [
  {
    toolkit: "slack",
    label: "Slack",
    description: "Post updates to Slack channels or DMs",
    authConfigId: process.env.COMPOSIO_SLACK_AUTH_CONFIG_ID,
  },
  {
    toolkit: "linear",
    label: "Linear",
    description: "Create or update issues in Linear",
    authConfigId: process.env.COMPOSIO_LINEAR_AUTH_CONFIG_ID,
    scopes: ["admin", "read", "write", "issues:create", "comments:create"],
  },
  {
    toolkit: "hubspot",
    label: "HubSpot",
    description: "Manage HubSpot contacts, deals, and tickets",
    authConfigId: process.env.COMPOSIO_HUBSPOT_AUTH_CONFIG_ID,
    scopes: [
      "account-info.security.read",
      "accounting",
      "cms.domains.read",
      "cms.domains.write",
      "crm.export",
      "crm.import",
      "crm.lists.read",
      "crm.lists.write",
      "crm.objects.companies.read",
      "crm.objects.companies.write",
      "crm.objects.contacts.read",
      "crm.objects.contacts.write",
      "crm.objects.deals.read",
      "crm.objects.deals.write",
      "crm.objects.marketing_events.read",
      "crm.objects.marketing_events.write",
      "crm.objects.owners.read",
      "crm.objects.quotes.read",
      "crm.objects.quotes.write",
      "crm.schemas.companies.read",
      "crm.schemas.companies.write",
      "crm.schemas.contacts.read",
      "crm.schemas.contacts.write",
      "oauth",
      "settings.users.read",
      "settings.users.write",
      "tickets",
      "timeline",
      "e-commerce",
      "crm.objects.custom.read",
      "crm.schemas.custom.read",
      "content",
      "sales-email-read",
    ],
  },
  {
    toolkit: "salesforce",
    label: "Salesforce",
    description: "Sync Salesforce leads and opportunities",
    authConfigId: process.env.COMPOSIO_SALESFORCE_AUTH_CONFIG_ID,
    scopes: ["full", "refresh_token"],
  },
  {
    toolkit: "apollo",
    label: "Apollo",
    description: "Sequence or enrich prospects via Apollo",
    authConfigId: process.env.COMPOSIO_APOLLO_AUTH_CONFIG_ID,
  },
  {
    toolkit: "zoominfo",
    label: "ZoomInfo",
    description: "Enrich records with ZoomInfo data",
    authConfigId: process.env.COMPOSIO_ZOOMINFO_AUTH_CONFIG_ID,
  },
  {
    toolkit: "notion",
    label: "Notion",
    description: "Log notes and insights in Notion",
    authConfigId: process.env.COMPOSIO_NOTION_AUTH_CONFIG_ID,
  },
  {
    toolkit: "airtable",
    label: "Airtable",
    description: "Store leads in Airtable bases",
    authConfigId: process.env.COMPOSIO_AIRTABLE_AUTH_CONFIG_ID,
    scopes: [
      "data.records:read",
      "data.records:write",
      "data.recordComments:read",
      "data.recordComments:write",
      "schema.bases:read",
      "schema.bases:write",
      "user.email:read",
    ],
  },
  {
    toolkit: "googlesheets",
    label: "Google Sheets",
    description: "Append rows to Google Sheets",
    authConfigId: process.env.COMPOSIO_GOOGLESHEETS_AUTH_CONFIG_ID,
    scopes: [
      "https://www.googleapis.com/auth/spreadsheets",
      "https://www.googleapis.com/auth/drive",
      "https://www.googleapis.com/auth/userinfo.email",
    ],
  },
  {
    toolkit: "googlebigquery",
    label: "BigQuery",
    description: "Load data into BigQuery",
    authConfigId: process.env.COMPOSIO_GOOGLEBIGQUERY_AUTH_CONFIG_ID,
  },
  {
    toolkit: "mailchimp",
    label: "Mailchimp",
    description: "Add subscribers or trigger campaigns",
    authConfigId: process.env.COMPOSIO_MAILCHIMP_AUTH_CONFIG_ID,
  },
  {
    toolkit: "customerio",
    label: "Customer.io",
    description: "Trigger Customer.io automations",
    authConfigId: process.env.COMPOSIO_CUSTOMERIO_AUTH_CONFIG_ID,
  },
  {
    toolkit: "microsoft_teams",
    label: "Microsoft Teams",
    description: "Notify channels in Microsoft Teams",
    authConfigId:
      process.env.COMPOSIO_MICROSOFT_TEAMS_AUTH_CONFIG_ID ||
      process.env.COMPOSIO_MICROSOFTTEAMS_AUTH_CONFIG_ID,
    scopes: [
      "Channel.Create",
      "Channel.ReadBasic.All",
      "ChannelMessage.Read.All",
      "ChannelMessage.ReadWrite",
      "ChannelMessage.Send",
      "ChannelSettings.ReadWrite.All",
      "Chat.Create",
      "Chat.Read",
      "Chat.ReadBasic",
      "Chat.ReadWrite",
      "Chat.ReadWrite.All",
      "ChatMessage.Read",
      "ChatMessage.Send",
      "Directory.ReadWrite.All",
      "Group.ReadWrite.All",
      "offline_access",
      "People.Read.All",
      "Presence.ReadWrite",
      "Team.Create",
      "Team.ReadBasic.All",
      "TeamMember.ReadWrite.All",
      "TeamsActivity.Read",
      "TeamsActivity.Send",
      "User.Read",
      "OnlineMeetings.ReadWrite",
    ],
  },
  {
    toolkit: "asana",
    label: "Asana",
    description: "Create follow-up tasks in Asana",
    authConfigId: process.env.COMPOSIO_ASANA_AUTH_CONFIG_ID,
  },
  {
    toolkit: "trello",
    label: "Trello",
    description: "Add cards to Trello boards",
    authConfigId: process.env.COMPOSIO_TRELLO_AUTH_CONFIG_ID,
    scopes: ["read", "write", "account"],
  },
  {
    toolkit: "monday",
    label: "Monday.com",
    description: "Manage requests on Monday boards",
    authConfigId: process.env.COMPOSIO_MONDAY_AUTH_CONFIG_ID,
  },
  {
    toolkit: "jira",
    label: "Jira",
    description: "Create Jira issues for feedback",
    authConfigId: process.env.COMPOSIO_JIRA_AUTH_CONFIG_ID,
    scopes: [
      "read:jira-work",
      "write:jira-work",
      "manage:jira-project",
      "manage:jira-configuration",
      "read:jira-user",
      "manage:jira-webhook",
      "manage:jira-data-provider",
      "read:servicedesk-request",
      "manage:servicedesk-customer",
      "write:servicedesk-request",
      "read:servicemanagement-insight-objects",
      "offline_access",
      "read:sprint:jira-software",
      "write:sprint:jira-software",
      "read:board-scope:jira-software",
      "write:board-scope:jira-software",
      "read:project:jira",
      "read:issue-type-scheme:jira",
    ],
  },
  {
    toolkit: "gong",
    label: "Gong",
    description: "Log calls and tasks in Gong",
    authConfigId: process.env.COMPOSIO_GONG_AUTH_CONFIG_ID,
    scopes: [
      "api:calls:read:transcript",
      "api:provisioning:read",
      "api:workspaces:read",
      "api:meetings:user:delete",
      "api:crm:get-objects",
      "api:data-privacy:delete",
      "api:crm:schema",
      "api:flows:write",
      "api:crm:upload",
      "api:meetings:integration:status",
      "api:calls:read:extensive",
      "api:meetings:user:update",
      "api:integration-settings:write",
      "api:settings:scorecards:read",
      "api:stats:scorecards",
      "api:stats:interaction",
      "api:stats:user-actions",
      "api:crm:integration:delete",
      "api:calls:read:basic",
      "api:calls:read:media-url",
      "api:tasks:read",
      "api:digital-interactions:write",
      "api:crm:integrations:read",
      "api:library:read",
      "api:data-privacy:read",
      "api:users:read",
      "api:tasks:write",
      "api:logs:read",
      "api:calls:create",
      "api:meetings:user:create",
      "api:stats:user-actions:detailed",
      "api:settings:trackers:read",
      "api:crm:integration:register",
      "api:provisioning:read-write",
      "api:engagement-data:write",
      "api:permission-profile:read",
      "api:permission-profile:write",
      "api:flows:read",
      "api:crm-calls:manual-association:read",
      "api:call-outcomes:read",
    ],
  },
  {
    toolkit: "zoom",
    label: "Zoom",
    description: "Register attendees for Zoom meetings",
    authConfigId: process.env.COMPOSIO_ZOOM_AUTH_CONFIG_ID,
    scopes: [
      "contact:read:list_contacts",
      "meeting:read:summary",
      "meeting:read:list_registrants",
      "meeting:read:list_past_participants",
      "meeting:read:list_meetings",
      "meeting:write:meeting",
      "meeting:update:meeting",
      "meeting:write:registrant",
      "meeting:read:meeting",
      "webinar:read:webinar",
      "webinar:read:list_registrants",
      "webinar:read:list_webinars",
      "webinar:read:list_past_participants",
      "webinar:read:participant",
      "webinar:write:registrant",
      "archiving:read:archived_files",
      "archiving:read:list_archived_files",
      "cloud_recording:delete:meeting_transcript",
      "cloud_recording:read:meeting_transcript",
      "cloud_recording:read:list_user_recordings",
      "cloud_recording:read:list_recording_registrants",
      "cloud_recording:read:list_recording_files",
      "user:read:list_collaboration_devices",
      "user:read:collaboration_device",
      "user:read:settings",
      "user:read:user",
    ],
  },
  {
    toolkit: "googleads",
    label: "Google Ads",
    description: "Manage audiences in Google Ads",
    authConfigId: process.env.COMPOSIO_GOOGLEADS_AUTH_CONFIG_ID,
    scopes: ["https://www.googleapis.com/auth/adwords"],
  },
  {
    toolkit: "metaads",
    label: "Meta Ads",
    description: "Update Meta Ads audiences",
    authConfigId: process.env.COMPOSIO_METAADS_AUTH_CONFIG_ID,
    scopes: ["ads_read", "ads_management"],
  },
  {
    toolkit: "calendly",
    label: "Calendly",
    description: "Schedule meetings via Calendly",
    authConfigId: process.env.COMPOSIO_CALENDLY_AUTH_CONFIG_ID,
  },
  {
    toolkit: "survey_monkey",
    label: "SurveyMonkey",
    description: "Send surveys with SurveyMonkey",
    authConfigId:
      process.env.COMPOSIO_SURVEY_MONKEY_AUTH_CONFIG_ID ||
      process.env.COMPOSIO_SURVEYMONKEY_AUTH_CONFIG_ID,
    scopes: ["surveys_read", "surveys_write"],
  },
]

// NOTE: Configuration via ACTIONS_COMPOSIO_TOOLKITS has been removed
// to avoid environment drift. The curated SUPPORTED_TOOLKITS below
// defines supported toolkits and scopes.

export function getAllowedComposioToolkits(): ToolkitDescriptor[] {
  if (!isComposioEnabled()) {
    return []
  }
  // Environment override removed. Use curated, supported toolkit list.
  return SUPPORTED_TOOLKITS.map((entry) => ({
    provider: "composio" as ActionProvider,
    ...entry,
  }))
}
