import { cn } from "../../lib/utils";

export interface ThemeStyles {
  container: string;
  option: string;
  selected: string;
  highlighted: string;
  label: string;
  hints: string;
  letterHint: string;
  numberHint: string;
  radio: string;
  checkbox: string;
  input: string;
  hint: string;
  footer: string;
  submitButton: string;
  optionsGrid: string;
  optionButton: string;
  moreButton: string;
  inputWrapper: string;
  sendButton: string;
  sendIcon: string;
  optionsWrapper: string;
  chip: string;
  checkIcon: string;
  selectionCount: string;
  ratingContainer: string;
  ratingButton: string;
  icon: string;
  active: string;
  hovered: string;
  keyHint: string;
  number: string;
  selectedText: string;
  compact: string;
  quickDates: string;
  quickDateButton: string;
  customDateButton: string;
  calendarWrapper: string;
  backButton: string;
  calendar: string;
  todayButton: string;
  selectedDate: string;
  dropzone: string;
  dragging: string;
  content: string;
  iconWrapper: string;
  uploadIcon: string;
  mainText: string;
  subText: string;
  browseButton: string;
  sizeHint: string;
  fileList: string;
  fileItem: string;
  fileName: string;
  fileSize: string;
  removeButton: string;
  progressBar: string;
  progressFill: string;
  uploadButton: string;
  hiddenInput: string;
  preview: string;
  fileInfo: string;
}

// TypeForm mode styles
const typeformStyles: Record<string, ThemeStyles> = {
  textInput: {
    container: "w-full space-y-4",
    input: cn(
      "w-full px-0 py-3 text-2xl md:text-3xl font-light",
      "bg-transparent border-0 border-b-2 border-border/30",
      "focus:border-primary focus:outline-none transition-colors duration-200",
      "placeholder:text-muted-foreground/50",
    ),
    hint: "text-sm text-muted-foreground flex items-center gap-2 mt-3",
    // Unused styles for this component
    option: "",
    selected: "",
    highlighted: "",
    label: "",
    hints: "",
    letterHint: "",
    numberHint: "",
    radio: "",
    checkbox: "",
    footer: "",
    submitButton: "",
    optionsGrid: "",
    optionButton: "",
    moreButton: "",
    inputWrapper: "",
    sendButton: "",
    sendIcon: "",
    optionsWrapper: "",
    chip: "",
    checkIcon: "",
    selectionCount: "",
    ratingContainer: "",
    ratingButton: "",
    icon: "",
    active: "",
    hovered: "",
    keyHint: "",
    number: "",
    selectedText: "",
    compact: "",
    quickDates: "",
    quickDateButton: "",
    customDateButton: "",
    calendarWrapper: "",
    backButton: "",
    calendar: "",
    todayButton: "",
    selectedDate: "",
    dropzone: "",
    dragging: "",
    content: "",
    iconWrapper: "",
    uploadIcon: "",
    mainText: "",
    subText: "",
    browseButton: "",
    sizeHint: "",
    fileList: "",
    fileItem: "",
    fileName: "",
    fileSize: "",
    removeButton: "",
    progressBar: "",
    progressFill: "",
    uploadButton: "",
    hiddenInput: "",
    preview: "",
    fileInfo: "",
  },
  select: {
    container: "w-full space-y-3",
    option: cn(
      "group relative flex items-center gap-4 p-4 rounded-lg",
      "border-2 border-border/50 bg-card/50 backdrop-blur",
      "cursor-pointer transition-all duration-200",
      "hover:border-primary/50 hover:bg-card/80",
      "focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2",
    ),
    selected: "border-primary bg-primary/10 hover:bg-primary/15",
    highlighted: "ring-2 ring-primary ring-offset-2",
    radio: "flex-shrink-0 w-5 h-5",
    label: "flex-1 text-base font-medium",
    hints: "flex items-center gap-2",
    letterHint: cn(
      "px-2 py-1 text-xs font-medium",
      "bg-muted/50 text-muted-foreground rounded",
      "border border-border/50",
    ),
    numberHint: cn(
      "px-2 py-1 text-xs font-medium",
      "bg-muted/50 text-muted-foreground rounded",
      "border border-border/50",
    ),
    // Unused styles
    checkbox: "",
    input: "",
    hint: "",
    footer: "",
    submitButton: "",
    optionsGrid: "",
    optionButton: "",
    moreButton: "",
    inputWrapper: "",
    sendButton: "",
    sendIcon: "",
    optionsWrapper: "",
    chip: "",
    checkIcon: "",
    selectionCount: "",
    ratingContainer: "",
    ratingButton: "",
    icon: "",
    active: "",
    hovered: "",
    keyHint: "",
    number: "",
    selectedText: "",
    compact: "",
    quickDates: "",
    quickDateButton: "",
    customDateButton: "",
    calendarWrapper: "",
    backButton: "",
    calendar: "",
    todayButton: "",
    selectedDate: "",
    dropzone: "",
    dragging: "",
    content: "",
    iconWrapper: "",
    uploadIcon: "",
    mainText: "",
    subText: "",
    browseButton: "",
    sizeHint: "",
    fileList: "",
    fileItem: "",
    fileName: "",
    fileSize: "",
    removeButton: "",
    progressBar: "",
    progressFill: "",
    uploadButton: "",
    hiddenInput: "",
    preview: "",
    fileInfo: "",
  },
  multiSelect: {
    container: "w-full space-y-4",
    optionsWrapper:
      "max-h-96 rounded-lg border border-border/50 bg-card/50 backdrop-blur",
    option: cn(
      "group relative flex items-center gap-4 p-4",
      "border-b border-border/30 last:border-b-0",
      "cursor-pointer transition-all duration-200",
      "hover:bg-accent/50",
    ),
    selected: "bg-primary/10 hover:bg-primary/15",
    highlighted: "bg-accent",
    checkbox: cn(
      "flex-shrink-0 w-5 h-5 rounded",
      "border-2 border-border/50",
      "transition-all duration-200",
    ),
    label: "flex-1 text-base font-medium",
    hints: "flex items-center gap-2",
    letterHint: cn(
      "px-2 py-1 text-xs font-medium",
      "bg-muted/50 text-muted-foreground rounded",
      "border border-border/50",
    ),
    footer: "flex items-center justify-between pt-4 border-t border-border/50",
    selectionCount: "text-sm text-muted-foreground",
    submitButton: cn(
      "inline-flex items-center gap-2 px-4 py-2 rounded-md",
      "bg-primary text-primary-foreground font-medium",
      "hover:bg-primary/90 transition-colors duration-200",
      "focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2",
    ),
    // Unused styles
    input: "",
    hint: "",
    radio: "",
    numberHint: "",
    optionsGrid: "",
    optionButton: "",
    moreButton: "",
    inputWrapper: "",
    sendButton: "",
    sendIcon: "",
    chip: "",
    checkIcon: "",
    ratingContainer: "",
    ratingButton: "",
    icon: "",
    active: "",
    hovered: "",
    keyHint: "",
    number: "",
    selectedText: "",
    compact: "",
    quickDates: "",
    quickDateButton: "",
    customDateButton: "",
    calendarWrapper: "",
    backButton: "",
    calendar: "",
    todayButton: "",
    selectedDate: "",
    dropzone: "",
    dragging: "",
    content: "",
    iconWrapper: "",
    uploadIcon: "",
    mainText: "",
    subText: "",
    browseButton: "",
    sizeHint: "",
    fileList: "",
    fileItem: "",
    fileName: "",
    fileSize: "",
    removeButton: "",
    progressBar: "",
    progressFill: "",
    uploadButton: "",
    hiddenInput: "",
    preview: "",
    fileInfo: "",
  },
  rating: {
    container: "w-full max-w-2xl mx-auto",
    ratingContainer: "flex items-center justify-center gap-2",
    ratingButton: cn(
      "group relative p-2 rounded-lg",
      "transition-all duration-200",
      "hover:bg-accent focus:outline-none focus:ring-2 focus:ring-ring",
    ),
    icon: cn(
      "w-10 h-10 transition-all duration-200",
      "text-border/50 group-hover:text-primary/50",
    ),
    active: "text-primary",
    hint: "text-sm text-muted-foreground text-center mt-4",
    // Unused styles
    option: "",
    selected: "",
    highlighted: "",
    label: "",
    hints: "",
    letterHint: "",
    numberHint: "",
    radio: "",
    checkbox: "",
    input: "",
    footer: "",
    submitButton: "",
    optionsGrid: "",
    optionButton: "",
    moreButton: "",
    inputWrapper: "",
    sendButton: "",
    sendIcon: "",
    optionsWrapper: "",
    chip: "",
    checkIcon: "",
    selectionCount: "",
    hovered: "",
    keyHint: "",
    number: "",
    selectedText: "",
    compact: "",
    quickDates: "",
    quickDateButton: "",
    customDateButton: "",
    calendarWrapper: "",
    backButton: "",
    calendar: "",
    todayButton: "",
    selectedDate: "",
    dropzone: "",
    dragging: "",
    content: "",
    iconWrapper: "",
    uploadIcon: "",
    mainText: "",
    subText: "",
    browseButton: "",
    sizeHint: "",
    fileList: "",
    fileItem: "",
    fileName: "",
    fileSize: "",
    removeButton: "",
    progressBar: "",
    progressFill: "",
    uploadButton: "",
    hiddenInput: "",
    preview: "",
    fileInfo: "",
  },
  linearScale: {
    container: "w-full max-w-3xl mx-auto space-y-6",
    optionsGrid: "grid grid-cols-auto-fit gap-3",
    optionButton: cn(
      "relative min-w-[60px] p-4 rounded-lg",
      "border-2 border-border/50 bg-card/50",
      "text-lg font-medium text-center",
      "cursor-pointer transition-all duration-200",
      "hover:border-primary/50 hover:bg-card/80",
      "focus:outline-none focus:ring-2 focus:ring-ring",
    ),
    selected: "border-primary bg-primary/10 hover:bg-primary/15",
    label: "block text-sm text-muted-foreground text-center mt-2",
    // Unused styles
    option: "",
    highlighted: "",
    hints: "",
    letterHint: "",
    numberHint: "",
    radio: "",
    checkbox: "",
    input: "",
    hint: "",
    footer: "",
    submitButton: "",
    moreButton: "",
    inputWrapper: "",
    sendButton: "",
    sendIcon: "",
    optionsWrapper: "",
    chip: "",
    checkIcon: "",
    selectionCount: "",
    ratingContainer: "",
    ratingButton: "",
    icon: "",
    active: "",
    hovered: "",
    keyHint: "",
    number: "",
    selectedText: "",
    compact: "",
    quickDates: "",
    quickDateButton: "",
    customDateButton: "",
    calendarWrapper: "",
    backButton: "",
    calendar: "",
    todayButton: "",
    selectedDate: "",
    dropzone: "",
    dragging: "",
    content: "",
    iconWrapper: "",
    uploadIcon: "",
    mainText: "",
    subText: "",
    browseButton: "",
    sizeHint: "",
    fileList: "",
    fileItem: "",
    fileName: "",
    fileSize: "",
    removeButton: "",
    progressBar: "",
    progressFill: "",
    uploadButton: "",
    hiddenInput: "",
    preview: "",
    fileInfo: "",
  },
};

// Chat mode styles - smaller and more subtle for embedding
const chatStyles: Record<string, ThemeStyles> = {
  textInput: {
    container: "w-full space-y-3",
    input: cn(
      "w-full px-4 py-3 text-base",
      "bg-card border-2 border-border/50 rounded-lg",
      "focus:border-primary focus:outline-none transition-colors duration-200",
      "placeholder:text-muted-foreground/50",
    ),
    hint: "text-sm text-muted-foreground",
    // Unused styles for this component
    option: "",
    selected: "",
    highlighted: "",
    label: "",
    hints: "",
    letterHint: "",
    numberHint: "",
    radio: "",
    checkbox: "",
    footer: "",
    submitButton: "",
    optionsGrid: "",
    optionButton: "",
    moreButton: "",
    inputWrapper: "",
    sendButton: "",
    sendIcon: "",
    optionsWrapper: "",
    chip: "",
    checkIcon: "",
    selectionCount: "",
    ratingContainer: "",
    ratingButton: "",
    icon: "",
    active: "",
    hovered: "",
    keyHint: "",
    number: "",
    selectedText: "",
    compact: "",
    quickDates: "",
    quickDateButton: "",
    customDateButton: "",
    calendarWrapper: "",
    backButton: "",
    calendar: "",
    todayButton: "",
    selectedDate: "",
    dropzone: "",
    dragging: "",
    content: "",
    iconWrapper: "",
    uploadIcon: "",
    mainText: "",
    subText: "",
    browseButton: "",
    sizeHint: "",
    fileList: "",
    fileItem: "",
    fileName: "",
    fileSize: "",
    removeButton: "",
    progressBar: "",
    progressFill: "",
    uploadButton: "",
    hiddenInput: "",
    preview: "",
    fileInfo: "",
  },
  select: {
    container: "w-full space-y-3",
    option: cn(
      "group relative flex items-center gap-3 p-3 rounded-lg",
      "border-2 border-border/50 bg-card",
      "cursor-pointer transition-all duration-200",
      "hover:border-primary/50 hover:bg-muted/50",
      "focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2",
    ),
    selected: "border-primary bg-primary/10 hover:bg-primary/15",
    highlighted: "ring-2 ring-primary ring-offset-2",
    radio: "flex-shrink-0 w-5 h-5",
    label: "flex-1 text-sm font-medium",
    hints: "hidden", // No keyboard hints in chat mode
    letterHint: "hidden",
    numberHint: "hidden",
    // Unused styles
    checkbox: "",
    input: "",
    hint: "",
    footer: "",
    submitButton: "",
    optionsGrid: "",
    optionButton: "",
    moreButton: "",
    inputWrapper: "",
    sendButton: "",
    sendIcon: "",
    optionsWrapper: "",
    chip: "",
    checkIcon: "",
    selectionCount: "",
    ratingContainer: "",
    ratingButton: "",
    icon: "",
    active: "",
    hovered: "",
    keyHint: "",
    number: "",
    selectedText: "",
    compact: "",
    quickDates: "",
    quickDateButton: "",
    customDateButton: "",
    calendarWrapper: "",
    backButton: "",
    calendar: "",
    todayButton: "",
    selectedDate: "",
    dropzone: "",
    dragging: "",
    content: "",
    iconWrapper: "",
    uploadIcon: "",
    mainText: "",
    subText: "",
    browseButton: "",
    sizeHint: "",
    fileList: "",
    fileItem: "",
    fileName: "",
    fileSize: "",
    removeButton: "",
    progressBar: "",
    progressFill: "",
    uploadButton: "",
    hiddenInput: "",
    preview: "",
    fileInfo: "",
  },
  multiSelect: {
    container: "w-full space-y-3",
    optionsWrapper: "space-y-3",
    option: cn(
      "group relative flex items-center gap-3 p-3 rounded-lg",
      "border-2 border-border/50 bg-card",
      "cursor-pointer transition-all duration-200",
      "hover:border-primary/50 hover:bg-muted/50",
    ),
    selected: "bg-primary/10 border-primary",
    highlighted: "ring-2 ring-primary ring-offset-2",
    checkbox: cn(
      "flex-shrink-0 w-5 h-5 rounded",
      "border-2 border-input",
      "transition-all duration-200",
    ),
    label: "flex-1 text-sm font-medium",
    hints: "hidden",
    letterHint: "hidden",
    footer:
      "flex items-center justify-between pt-3 text-sm text-muted-foreground",
    selectionCount: "text-sm text-muted-foreground",
    submitButton: cn(
      "inline-flex items-center gap-2 px-4 py-2 rounded-md",
      "bg-primary text-primary-foreground font-medium",
      "hover:bg-primary/90 transition-colors duration-200",
      "focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2",
    ),
    // Unused styles
    input: "",
    hint: "",
    radio: "",
    numberHint: "",
    optionsGrid: "",
    optionButton: "",
    moreButton: "",
    inputWrapper: "",
    sendButton: "",
    sendIcon: "",
    chip: "",
    checkIcon: "",
    ratingContainer: "",
    ratingButton: "",
    icon: "",
    active: "",
    hovered: "",
    keyHint: "",
    number: "",
    selectedText: "",
    compact: "",
    quickDates: "",
    quickDateButton: "",
    customDateButton: "",
    calendarWrapper: "",
    backButton: "",
    calendar: "",
    todayButton: "",
    selectedDate: "",
    dropzone: "",
    dragging: "",
    content: "",
    iconWrapper: "",
    uploadIcon: "",
    mainText: "",
    subText: "",
    browseButton: "",
    sizeHint: "",
    fileList: "",
    fileItem: "",
    fileName: "",
    fileSize: "",
    removeButton: "",
    progressBar: "",
    progressFill: "",
    uploadButton: "",
    hiddenInput: "",
    preview: "",
    fileInfo: "",
  },
  rating: {
    container: "w-full",
    ratingContainer: "flex items-center justify-center gap-3",
    ratingButton: cn(
      "group relative p-2 rounded-lg",
      "transition-all duration-200",
      "hover:bg-muted/50 focus:outline-none focus:ring-2 focus:ring-ring",
    ),
    icon: cn(
      "w-10 h-10 transition-all duration-200",
      "text-muted-foreground/50 group-hover:scale-110",
    ),
    active: "text-primary",
    hint: "hidden", // No keyboard hints in chat mode
    // Unused styles
    option: "",
    selected: "",
    highlighted: "",
    label: "",
    hints: "",
    letterHint: "",
    numberHint: "",
    radio: "",
    checkbox: "",
    input: "",
    footer: "",
    submitButton: "",
    optionsGrid: "",
    optionButton: "",
    moreButton: "",
    inputWrapper: "",
    sendButton: "",
    sendIcon: "",
    optionsWrapper: "",
    chip: "",
    checkIcon: "",
    selectionCount: "",
    hovered: "",
    keyHint: "",
    number: "",
    selectedText: "",
    compact: "",
    quickDates: "",
    quickDateButton: "",
    customDateButton: "",
    calendarWrapper: "",
    backButton: "",
    calendar: "",
    todayButton: "",
    selectedDate: "",
    dropzone: "",
    dragging: "",
    content: "",
    iconWrapper: "",
    uploadIcon: "",
    mainText: "",
    subText: "",
    browseButton: "",
    sizeHint: "",
    fileList: "",
    fileItem: "",
    fileName: "",
    fileSize: "",
    removeButton: "",
    progressBar: "",
    progressFill: "",
    uploadButton: "",
    hiddenInput: "",
    preview: "",
    fileInfo: "",
  },
  linearScale: {
    container: "w-full space-y-4",
    optionsGrid: "flex flex-wrap gap-2 justify-center",
    optionButton: cn(
      "relative min-w-[48px] p-3 rounded-lg",
      "border-2 border-border/50 bg-card",
      "text-sm font-medium text-center",
      "cursor-pointer transition-all duration-200",
      "hover:border-primary/50 hover:bg-muted/50",
      "focus:outline-none focus:ring-2 focus:ring-ring",
    ),
    selected: "border-primary bg-primary/10 hover:bg-primary/15",
    label: "block text-xs text-muted-foreground text-center mt-2",
    // Unused styles
    option: "",
    highlighted: "",
    hints: "",
    letterHint: "",
    numberHint: "",
    radio: "",
    checkbox: "",
    input: "",
    hint: "",
    footer: "",
    submitButton: "",
    moreButton: "",
    inputWrapper: "",
    sendButton: "",
    sendIcon: "",
    optionsWrapper: "",
    chip: "",
    checkIcon: "",
    selectionCount: "",
    ratingContainer: "",
    ratingButton: "",
    icon: "",
    active: "",
    hovered: "",
    keyHint: "",
    number: "",
    selectedText: "",
    compact: "",
    quickDates: "",
    quickDateButton: "",
    customDateButton: "",
    calendarWrapper: "",
    backButton: "",
    calendar: "",
    todayButton: "",
    selectedDate: "",
    dropzone: "",
    dragging: "",
    content: "",
    iconWrapper: "",
    uploadIcon: "",
    mainText: "",
    subText: "",
    browseButton: "",
    sizeHint: "",
    fileList: "",
    fileItem: "",
    fileName: "",
    fileSize: "",
    removeButton: "",
    progressBar: "",
    progressFill: "",
    uploadButton: "",
    hiddenInput: "",
    preview: "",
    fileInfo: "",
  },
};

export function useThemeStyles(
  component: string,
  mode: "typeform" | "chat",
): ThemeStyles {
  const styles = mode === "typeform" ? typeformStyles : chatStyles;

  // Return the component styles or empty strings for all properties
  return (
    styles[component] || {
      container: "",
      option: "",
      selected: "",
      highlighted: "",
      label: "",
      hints: "",
      letterHint: "",
      numberHint: "",
      radio: "",
      checkbox: "",
      input: "",
      hint: "",
      footer: "",
      submitButton: "",
      optionsGrid: "",
      optionButton: "",
      moreButton: "",
      inputWrapper: "",
      sendButton: "",
      sendIcon: "",
      optionsWrapper: "",
      chip: "",
      checkIcon: "",
      selectionCount: "",
      ratingContainer: "",
      ratingButton: "",
      icon: "",
      active: "",
      hovered: "",
      keyHint: "",
      number: "",
      selectedText: "",
      compact: "",
      quickDates: "",
      quickDateButton: "",
      customDateButton: "",
      calendarWrapper: "",
      backButton: "",
      calendar: "",
      todayButton: "",
      selectedDate: "",
      dropzone: "",
      dragging: "",
      content: "",
      iconWrapper: "",
      uploadIcon: "",
      mainText: "",
      subText: "",
      browseButton: "",
      sizeHint: "",
      fileList: "",
      fileItem: "",
      fileName: "",
      fileSize: "",
      removeButton: "",
      progressBar: "",
      progressFill: "",
      uploadButton: "",
      hiddenInput: "",
      preview: "",
      fileInfo: "",
    }
  );
}
