SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE TYPE "public"."form_status" AS ENUM (
    'draft',
    'published',
    'archived'
);


ALTER TYPE "public"."form_status" OWNER TO "postgres";


CREATE TYPE "public"."submission_status" AS ENUM (
    'in_progress',
    'completed',
    'abandoned'
);


ALTER TYPE "public"."submission_status" OWNER TO "postgres";

CREATE TYPE public.action_provider AS ENUM ('usesend', 'composio');

SET default_tablespace = '';

SET default_table_access_method = "heap";


-- Organizations: top-level container (owner-scoped today)
CREATE TABLE IF NOT EXISTS "public"."organizations" (
    "org_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "slug" "text",
    "created_by" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "organizations_pkey" PRIMARY KEY ("org_id")
);

ALTER TABLE "public"."organizations" OWNER TO "postgres";

COMMENT ON TABLE "public"."organizations" IS 'Top-level container; one organization can have many workspaces.';

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes WHERE schemaname='public' AND tablename='organizations' AND indexname='organizations_slug_key'
  ) THEN
    CREATE UNIQUE INDEX "organizations_slug_key" ON "public"."organizations" ("slug");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_type = 'UNIQUE'
      AND table_schema = 'public'
      AND table_name = 'organizations'
      AND constraint_name = 'organizations_created_by_name_key'
  ) THEN
    ALTER TABLE "public"."organizations"
      ADD CONSTRAINT "organizations_created_by_name_key" UNIQUE ("created_by", "name");
  END IF;
END $$;
CREATE TABLE IF NOT EXISTS "public"."brands" (
    "brand_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "logo_url" "text",
    "theme" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "created_by" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "brands_pkey" PRIMARY KEY ("brand_id")
);


ALTER TABLE "public"."brands" OWNER TO "postgres";


COMMENT ON TABLE "public"."brands" IS 'Stores branding information (logo, theme) for forms.';



CREATE TABLE IF NOT EXISTS "public"."form_answers" (
    "answer_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "submission_id" "uuid" NOT NULL,
    "question_id" character varying(255) NOT NULL,
    "answer_value" "jsonb" NOT NULL,
    "chat_messages" "jsonb",
    "is_additional_field" boolean DEFAULT false,
    CONSTRAINT "form_answers_pkey" PRIMARY KEY ("answer_id"),
    CONSTRAINT "uq_answer_per_question_per_submission" UNIQUE ("submission_id", "question_id")
);


ALTER TABLE "public"."form_answers" OWNER TO "postgres";


COMMENT ON TABLE "public"."form_answers" IS 'Stores individual answers provided within a form submission.';



CREATE TABLE IF NOT EXISTS "public"."form_chat_attachments" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" DEFAULT "gen_random_uuid"(),
    "file_name" "text",
    "file_size" numeric,
    "file_url" "text",
    "file_type" "text",
    "form_id" "uuid",
    CONSTRAINT "form_chat_attachments_pkey" PRIMARY KEY ("id")
);


ALTER TABLE "public"."form_chat_attachments" OWNER TO "postgres";


ALTER TABLE "public"."form_chat_attachments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."form_chat_attachments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."form_submissions" (
    "submission_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "form_version_id" "uuid" NOT NULL,
    "user_id" "uuid",
    "status" "public"."submission_status" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "last_updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "completed_at" timestamp with time zone,
    "metadata" "jsonb",
    "testmode" boolean DEFAULT false NOT NULL,
    CONSTRAINT "form_submissions_pkey" PRIMARY KEY ("submission_id")
);


ALTER TABLE "public"."form_submissions" OWNER TO "postgres";


COMMENT ON TABLE "public"."form_submissions" IS 'Records each attempt or instance of filling out a form version.';



CREATE TABLE IF NOT EXISTS "public"."form_versions" (
    "version_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "form_id" "uuid" NOT NULL,
    "status" "public"."form_status" DEFAULT 'draft'::"public"."form_status" NOT NULL,
    "title" "jsonb" NOT NULL,
    "description" "jsonb",
    "questions" "jsonb" NOT NULL,
    "settings" "jsonb",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "published_at" timestamp with time zone,
    "archived_at" timestamp with time zone,
    "user_id" "uuid",
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "form_versions_pkey" PRIMARY KEY ("version_id")
);


ALTER TABLE "public"."form_versions" OWNER TO "postgres";


COMMENT ON TABLE "public"."form_versions" IS 'Stores specific versions (schema, elements) of a form.';



CREATE TABLE IF NOT EXISTS "public"."forms" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "brand_id" "uuid",
    "user_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "current_published_version_id" "uuid",
    "current_draft_version_id" "uuid",
    "short_id" "text",
    "agent_state" "jsonb",
    "workspace_id" "uuid" NOT NULL,
    CONSTRAINT "forms_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "forms_current_draft_version_id_key" UNIQUE ("current_draft_version_id"),
    CONSTRAINT "forms_current_published_version_id_key" UNIQUE ("current_published_version_id"),
    CONSTRAINT "forms_short_id_key" UNIQUE ("short_id")
);


ALTER TABLE "public"."forms" OWNER TO "postgres";


COMMENT ON TABLE "public"."forms" IS 'Represents the high-level form entity.';

-- Minimal multi-tenant future-proofing: workspaces + link from forms
-- Create workspaces table (owner-scoped; membership to be added later)
CREATE TABLE IF NOT EXISTS "public"."workspaces" (
    "workspace_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "org_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "created_by" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "workspaces_pkey" PRIMARY KEY ("workspace_id")
);

ALTER TABLE "public"."workspaces" OWNER TO "postgres";

COMMENT ON TABLE "public"."workspaces" IS 'Lightweight container to group forms; owner-scoped for now.';
COMMENT ON COLUMN "public"."forms"."workspace_id" IS 'Optional scope; when set, form belongs to this workspace.';

-- Unique personal workspace per user by name, to enable idempotent upsert
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_type = 'UNIQUE'
      AND table_schema = 'public'
      AND table_name = 'workspaces'
      AND constraint_name = 'workspaces_created_by_name_key'
  ) THEN
    ALTER TABLE "public"."workspaces"
      ADD CONSTRAINT "workspaces_created_by_name_key" UNIQUE ("created_by", "name");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_type = 'UNIQUE'
      AND table_schema = 'public'
      AND table_name = 'workspaces'
      AND constraint_name = 'workspaces_org_id_name_key'
  ) THEN
    ALTER TABLE "public"."workspaces"
      ADD CONSTRAINT "workspaces_org_id_name_key" UNIQUE ("org_id", "name");
  END IF;
END $$;

-- FK: workspaces.org_id → organizations.org_id
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_type = 'FOREIGN KEY'
      AND table_schema = 'public'
      AND table_name = 'workspaces'
      AND constraint_name = 'workspaces_org_id_fkey'
  ) THEN
    ALTER TABLE ONLY "public"."workspaces"
      ADD CONSTRAINT "workspaces_org_id_fkey"
      FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("org_id") ON DELETE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes WHERE schemaname='public' AND tablename='workspaces' AND indexname='workspaces_org_id_idx'
  ) THEN
    CREATE INDEX "workspaces_org_id_idx" ON "public"."workspaces" USING btree ("org_id");
  END IF;
END $$;



CREATE TABLE IF NOT EXISTS "public"."messages" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "role" "text",
    "user_id" "uuid",
    "parts" "jsonb",
    "attachments" "jsonb",
    "content" "jsonb",
    "form_id" "uuid",
    CONSTRAINT "messages_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "messages_role_check" CHECK (("role" = ANY (ARRAY['system'::"text", 'user'::"text", 'assistant'::"text", 'data'::"text"])))
);


ALTER TABLE "public"."messages" OWNER TO "postgres";


COMMENT ON TABLE "public"."messages" IS 'Stores individual messages within a chat.';



ALTER TABLE "public"."messages" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."messages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."submission_chat_attachments" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" DEFAULT "gen_random_uuid"(),
    "file_name" "text",
    "file_size" numeric,
    "file_url" "text",
    "file_type" "text",
    "submission_id" "uuid",
    CONSTRAINT "submission_chat_attachments_pkey" PRIMARY KEY ("id")
);


ALTER TABLE "public"."submission_chat_attachments" OWNER TO "postgres";


COMMENT ON TABLE "public"."submission_chat_attachments" IS 'This is a duplicate of form_chat_attachments';



ALTER TABLE "public"."submission_chat_attachments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."submission_chat_attachments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."submission_messages" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "role" "text",
    "user_id" "uuid",
    "parts" "jsonb",
    "attachments" "jsonb",
    "content" "jsonb",
    "submission_id" "uuid",
    CONSTRAINT "submission_messages_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "messages_role_check" CHECK (("role" = ANY (ARRAY['system'::"text", 'user'::"text", 'assistant'::"text", 'data'::"text"])))
);


ALTER TABLE "public"."submission_messages" OWNER TO "postgres";


ALTER TABLE "public"."submission_messages" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."submission_messages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."tasks" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "form_id" "uuid" NOT NULL,
    "task_definition" "jsonb" NOT NULL,
    "status" "text" DEFAULT 'pending'::"text" NOT NULL,
    "output" "jsonb",
    "error" "text",
    "retries" integer DEFAULT 0,
    "started_at" timestamp with time zone,
    "completed_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "tasks_pkey" PRIMARY KEY ("id")
);


ALTER TABLE "public"."tasks" OWNER TO "postgres";


COMMENT ON COLUMN "public"."tasks"."form_id" IS 'Foreign key linking to the parent form generation process';



COMMENT ON COLUMN "public"."tasks"."task_definition" IS 'JSON object describing the task (e.g., { type: "generate_schema", question_title: "..." })';



COMMENT ON COLUMN "public"."tasks"."status" IS 'Current status of the task execution';



COMMENT ON COLUMN "public"."tasks"."output" IS 'Result of the task if successful (e.g., generated schema)';



COMMENT ON COLUMN "public"."tasks"."error" IS 'Error message if the task failed';



CREATE TABLE IF NOT EXISTS "public"."usage_history" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "message_count" integer NOT NULL,
    "period_start" timestamp with time zone NOT NULL,
    "period_end" timestamp with time zone NOT NULL,
    CONSTRAINT "usage_history_pkey" PRIMARY KEY ("id")
);


ALTER TABLE "public"."usage_history" OWNER TO "postgres";


COMMENT ON TABLE "public"."usage_history" IS 'Tracks user message usage over periods.';



ALTER TABLE "public"."usage_history" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."usage_history_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" "uuid" NOT NULL,
    "email" "text" NOT NULL,
    "anonymous" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "daily_message_count" integer DEFAULT 0,
    "daily_reset" timestamp with time zone,
    "display_name" "text",
    "message_count" integer DEFAULT 0,
    "preferred_model" "text",
    "premium" boolean DEFAULT false,
    "profile_image" "text",
    CONSTRAINT "users_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "users_email_key" UNIQUE ("email")
);


ALTER TABLE "public"."users" OWNER TO "postgres";


COMMENT ON TABLE "public"."users" IS 'Stores user profile information, linked to auth.users.';


CREATE TABLE public.response_actions_log (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    form_id uuid NOT NULL,
    user_id uuid,
    submission_ids uuid[],
    action_name text NOT NULL,
    status text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    started_at timestamptz,
    completed_at timestamptz,
    provider public.action_provider NOT NULL DEFAULT 'usesend',
    view_id uuid,
    connected_account_id text,
    idempotency_key character varying(255),
    provider_response jsonb,
    params jsonb,
    result jsonb,
    error_message text,
    source text,
    tools_applied jsonb
);

-- (removed) actions_config: replaced by tool_connections (global auth) and
-- per-view action params stored in response_views.actions

CREATE TABLE public.response_views (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    form_id uuid NOT NULL,
    name text NOT NULL,
    description text,
    filters jsonb,
    columns jsonb,
    sort_config jsonb,
    insights_spec jsonb,
    action_slugs jsonb,
    actions jsonb,
    is_default boolean DEFAULT false,
    is_public boolean DEFAULT false,
    public_access_level text,
    public_api_key_required boolean,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- Global provider connections (auth is reused across forms)
CREATE TABLE public.tool_connections (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  provider public.action_provider NOT NULL DEFAULT 'composio',
  toolkit text NOT NULL,
  connected_account_id text,
  auth_status text NOT NULL DEFAULT 'unknown',
  pending_connection_request_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX tool_connections_user_provider_toolkit
  ON public.tool_connections (user_id, provider, toolkit);

CREATE INDEX tool_connections_user_id ON public.tool_connections (user_id);
CREATE INDEX tool_connections_pending_idx ON public.tool_connections (pending_connection_request_id);

CREATE TABLE public.formlink_api_keys (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    api_key text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);


CREATE INDEX "idx_brands_created_by" ON "public"."brands" USING "btree" ("created_by");



CREATE INDEX "idx_form_answers_question_id" ON "public"."form_answers" USING "btree" ("question_id");



CREATE INDEX "idx_form_answers_submission_id" ON "public"."form_answers" USING "btree" ("submission_id");



CREATE INDEX "idx_form_answers_submission_question" ON "public"."form_answers" USING "btree" ("submission_id", "question_id");



CREATE INDEX "idx_form_submissions_last_updated" ON "public"."form_submissions" USING "btree" ("last_updated_at");



CREATE INDEX "idx_form_submissions_status" ON "public"."form_submissions" USING "btree" ("status");



CREATE INDEX "idx_form_submissions_user_id" ON "public"."form_submissions" USING "btree" ("user_id");



CREATE INDEX "idx_form_submissions_version_id" ON "public"."form_submissions" USING "btree" ("form_version_id");



CREATE INDEX "idx_form_versions_form_id" ON "public"."form_versions" USING "btree" ("form_id");



CREATE INDEX "idx_form_versions_status" ON "public"."form_versions" USING "btree" ("form_id", "status");



CREATE INDEX "idx_forms_brand_id" ON "public"."forms" USING "btree" ("brand_id");



CREATE INDEX "idx_forms_created_by" ON "public"."forms" USING "btree" ("user_id");

CREATE UNIQUE INDEX response_actions_log_idempotency_idx
  ON public.response_actions_log (form_id, action_name, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

-- Speed up lookups by submission membership
CREATE INDEX response_actions_log_submission_ids_gin
  ON public.response_actions_log USING GIN (submission_ids);

-- Sidecar mapping: actions log per submission for quick per-row history
CREATE TABLE public.submission_action_logs (
  submission_id uuid NOT NULL,
  action_log_id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (submission_id, action_log_id)
);

CREATE INDEX submission_action_logs_submission_idx ON public.submission_action_logs (submission_id);
CREATE INDEX submission_action_logs_action_idx ON public.submission_action_logs (action_log_id);

-- removed legacy actions_config index; table no longer exists


CREATE OR REPLACE FUNCTION "public"."check_anonymous_form_limit"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
  DECLARE
    form_count integer;
    user_email text;
  BEGIN
    -- Get user email to check if anonymous
    SELECT email INTO user_email
    FROM public.users
    WHERE id = NEW.user_id;

    -- Check if user is anonymous (using Supabase's anonymous email pattern)
    IF user_email LIKE '%@anonymous.example' THEN
      -- Count existing forms
      SELECT COUNT(*) INTO form_count
      FROM public.forms
      WHERE user_id = NEW.user_id;

      -- Limit anonymous users to 3 forms
      IF form_count >= 3 THEN
        RAISE EXCEPTION 'Anonymous users are limited to 3 forms';
      END IF;
    END IF;

    RETURN NEW;
  END;
  $$;


ALTER FUNCTION "public"."check_anonymous_form_limit"() OWNER TO "postgres";
-- Pin search_path to empty string for security (lint 0011)
ALTER FUNCTION public.check_anonymous_form_limit() SET search_path = '';


-- NOTE: Removed legacy generate_short_id() that depended on a non-default
-- hashids extension. Application code generates short_id explicitly on insert.

-- Stub generate_short_id: legacy helper removed, keep no-op for compatibility
CREATE OR REPLACE FUNCTION public.generate_short_id()
RETURNS trigger AS $$
BEGIN
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
ALTER FUNCTION public.generate_short_id() SET search_path = '';


CREATE OR REPLACE FUNCTION "public"."get_filtered_submissions"("submission_filters" "jsonb", "answer_filters" "jsonb", "page" integer DEFAULT 1, "page_size" integer DEFAULT 50) RETURNS TABLE("data" "jsonb", "total_count" bigint, "total_completed_count" bigint, "total_in_progress_count" bigint, "total_filtered_count" bigint, "completed_count" bigint, "in_progress_count" bigint)
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  RETURN QUERY
  WITH filtered_submissions_base AS (
    -- This CTE selects submissions based on general submission-level filters.
    -- It selects the original UUIDs and other necessary fields for internal use.
    SELECT
        fs_inner.submission_id AS original_submission_id,
        fs_inner.form_version_id,
        fs_inner.user_id,
        fs_inner.created_at,
        fs_inner.completed_at,
        fs_inner.last_updated_at,
        fs_inner.status,
        fs_inner.testmode,
        fs_inner.metadata -> 'sidecar' AS sidecar
    FROM form_submissions fs_inner
    WHERE
      -- form_version_id equality
      ((submission_filters->>'form_version_id') IS NULL OR fs_inner.form_version_id = (submission_filters->>'form_version_id')::uuid)
      -- status equality or inclusion
      AND (
        (submission_filters->'status') IS NULL OR
        (jsonb_typeof(submission_filters->'status') = 'string' AND fs_inner.status = (submission_filters->>'status')::public.submission_status) OR
        (jsonb_typeof(submission_filters->'status') = 'array' AND fs_inner.status::text IN (
          SELECT jsonb_array_elements_text(submission_filters->'status')
        ))
      )
      -- user_id equality
      AND ((submission_filters->>'user_id') IS NULL OR fs_inner.user_id = (submission_filters->>'user_id')::uuid)
      -- created_at: string lower-bound OR object { since, before, between:[start,end] }
      AND (
        (submission_filters->'created_at') IS NULL OR
        (jsonb_typeof(submission_filters->'created_at') = 'string' AND fs_inner.created_at >= (submission_filters->>'created_at')::timestamptz) OR
        (jsonb_typeof(submission_filters->'created_at') = 'object' AND
          ((NOT (submission_filters->'created_at' ? 'since')) OR fs_inner.created_at >= (submission_filters->'created_at'->>'since')::timestamptz) AND
          ((NOT (submission_filters->'created_at' ? 'before')) OR fs_inner.created_at < (submission_filters->'created_at'->>'before')::timestamptz) AND
          ((NOT (submission_filters->'created_at' ? 'between')) OR (
            fs_inner.created_at >= (submission_filters->'created_at'->'between'->>0)::timestamptz AND
            fs_inner.created_at <= (submission_filters->'created_at'->'between'->>1)::timestamptz
          ))
        )
      )
      -- completed_at: object support similar to created_at (optional)
      AND (
        (submission_filters->'completed_at') IS NULL OR
        (jsonb_typeof(submission_filters->'completed_at') = 'string' AND fs_inner.completed_at >= (submission_filters->>'completed_at')::timestamptz) OR
        (jsonb_typeof(submission_filters->'completed_at') = 'object' AND
          ((NOT (submission_filters->'completed_at' ? 'since')) OR fs_inner.completed_at >= (submission_filters->'completed_at'->>'since')::timestamptz) AND
          ((NOT (submission_filters->'completed_at' ? 'before')) OR fs_inner.completed_at < (submission_filters->'completed_at'->>'before')::timestamptz) AND
          ((NOT (submission_filters->'completed_at' ? 'between')) OR (
            fs_inner.completed_at >= (submission_filters->'completed_at'->'between'->>0)::timestamptz AND
            fs_inner.completed_at <= (submission_filters->'completed_at'->'between'->>1)::timestamptz
          ))
        )
      )
      -- last_updated_at: object support similar to created_at (optional)
      AND (
        (submission_filters->'last_updated_at') IS NULL OR
        (jsonb_typeof(submission_filters->'last_updated_at') = 'string' AND fs_inner.last_updated_at >= (submission_filters->>'last_updated_at')::timestamptz) OR
        (jsonb_typeof(submission_filters->'last_updated_at') = 'object' AND
          ((NOT (submission_filters->'last_updated_at' ? 'since')) OR fs_inner.last_updated_at >= (submission_filters->'last_updated_at'->>'since')::timestamptz) AND
          ((NOT (submission_filters->'last_updated_at' ? 'before')) OR fs_inner.last_updated_at < (submission_filters->'last_updated_at'->>'before')::timestamptz) AND
          ((NOT (submission_filters->'last_updated_at' ? 'between')) OR (
            fs_inner.last_updated_at >= (submission_filters->'last_updated_at'->'between'->>0)::timestamptz AND
            fs_inner.last_updated_at <= (submission_filters->'last_updated_at'->'between'->>1)::timestamptz
          ))
        )
      )
      -- testmode boolean (allow string or boolean)
      AND (
        (submission_filters->'testmode') IS NULL OR
        (jsonb_typeof(submission_filters->'testmode') IN ('boolean','string') AND fs_inner.testmode = (submission_filters->>'testmode')::boolean)
      )
  ),
  relevant_filter_data AS (
    -- Pre-processes answer_filters to get question_id and their filter_criteria (JSONB values).
    SELECT key AS question_id, value AS filter_criteria
    FROM jsonb_each(answer_filters)
    WHERE answer_filters IS NOT NULL AND answer_filters != '{}'::jsonb
  ),
  answer_conditions AS (
    -- Identifies submissions and question_ids that match answer filter criteria, supporting advanced operators.
    SELECT DISTINCT
      a.submission_id,
      a.question_id
    FROM
      form_answers a
      JOIN relevant_filter_data rfd ON a.question_id = rfd.question_id
      LEFT JOIN LATERAL jsonb_array_elements(
        CASE WHEN jsonb_typeof(rfd.filter_criteria) = 'array' THEN rfd.filter_criteria ELSE NULL END
      ) AS arr_elem(val) ON TRUE
      LEFT JOIN LATERAL jsonb_array_elements(
        CASE WHEN jsonb_typeof(rfd.filter_criteria) = 'object' AND jsonb_typeof(rfd.filter_criteria->'in') = 'array' THEN rfd.filter_criteria->'in' ELSE NULL END
      ) AS in_elem(val) ON TRUE
      LEFT JOIN LATERAL jsonb_array_elements(
        CASE WHEN jsonb_typeof(rfd.filter_criteria) = 'object' AND jsonb_typeof(rfd.filter_criteria->'includes') = 'array' THEN rfd.filter_criteria->'includes' ELSE NULL END
      ) AS inc_elem(val) ON TRUE
      LEFT JOIN LATERAL jsonb_array_elements(
        CASE WHEN jsonb_typeof(rfd.filter_criteria) = 'object' AND jsonb_typeof(rfd.filter_criteria->'all') = 'array' THEN rfd.filter_criteria->'all' ELSE NULL END
      ) AS all_elem(val) ON TRUE
    WHERE
      (
        -- Basic array equals any element
        (jsonb_typeof(rfd.filter_criteria) = 'array' AND (
          a.answer_value = arr_elem.val OR
          (jsonb_typeof(a.answer_value) = 'array' AND EXISTS (
            SELECT 1 FROM jsonb_array_elements(a.answer_value) av WHERE av.value = arr_elem.val
          ))
        )) OR
        -- Simple equality
        (jsonb_typeof(rfd.filter_criteria) = 'string' AND a.answer_value = rfd.filter_criteria) OR
        (jsonb_typeof(rfd.filter_criteria) IN ('number','boolean') AND a.answer_value = rfd.filter_criteria) OR
        (jsonb_typeof(rfd.filter_criteria) = 'null' AND (a.answer_value IS NULL OR a.answer_value = 'null'::jsonb)) OR
        -- Object operators
        (jsonb_typeof(rfd.filter_criteria) = 'object' AND (
          -- eq
          (rfd.filter_criteria ? 'eq' AND a.answer_value = rfd.filter_criteria->'eq') OR
          -- in/includes (match if scalar equals any or array answer overlaps)
          (rfd.filter_criteria ? 'in' AND (
            a.answer_value = in_elem.val OR
            (jsonb_typeof(a.answer_value) = 'array' AND EXISTS (
              SELECT 1 FROM jsonb_array_elements(a.answer_value) av WHERE av.value = in_elem.val
            ))
          )) OR
          (rfd.filter_criteria ? 'includes' AND (
            a.answer_value = inc_elem.val OR
            (jsonb_typeof(a.answer_value) = 'array' AND EXISTS (
              SELECT 1 FROM jsonb_array_elements(a.answer_value) av WHERE av.value = inc_elem.val
            ))
          )) OR
          -- all (for array answers)
          (rfd.filter_criteria ? 'all' AND jsonb_typeof(a.answer_value) = 'array' AND NOT EXISTS (
            SELECT 1 FROM jsonb_array_elements(rfd.filter_criteria->'all') req
            WHERE NOT EXISTS (
              SELECT 1 FROM jsonb_array_elements(a.answer_value) av WHERE av.value = req.value
            )
          )) OR
          -- contains (substring match for text answers)
          (rfd.filter_criteria ? 'contains' AND jsonb_typeof(a.answer_value) = 'string' AND (
            (a.answer_value #>> '{}') ILIKE ('%' || (rfd.filter_criteria->>'contains') || '%')
          )) OR
          -- Numeric comparisons
          ((rfd.filter_criteria ? 'gte' OR rfd.filter_criteria ? 'gt' OR rfd.filter_criteria ? 'lte' OR rfd.filter_criteria ? 'lt' OR rfd.filter_criteria ? 'between') AND (
            CASE
              WHEN jsonb_typeof(a.answer_value) = 'number' THEN TRUE
              ELSE FALSE
            END
          ) AND (
            (rfd.filter_criteria ? 'gte' AND (a.answer_value #>> '{}')::numeric >= (rfd.filter_criteria->>'gte')::numeric) OR
            (rfd.filter_criteria ? 'gt'  AND (a.answer_value #>> '{}')::numeric >  (rfd.filter_criteria->>'gt')::numeric) OR
            (rfd.filter_criteria ? 'lte' AND (a.answer_value #>> '{}')::numeric <= (rfd.filter_criteria->>'lte')::numeric) OR
            (rfd.filter_criteria ? 'lt'  AND (a.answer_value #>> '{}')::numeric <  (rfd.filter_criteria->>'lt')::numeric) OR
            (rfd.filter_criteria ? 'between' AND (a.answer_value #>> '{}')::numeric >= (rfd.filter_criteria->'between'->>0)::numeric AND (a.answer_value #>> '{}')::numeric <= (rfd.filter_criteria->'between'->>1)::numeric)
          ))
        ))
      )
  ),
  submissions_meeting_filter_criteria AS (
    -- Counts distinct matched questions per submission and filters them.
    SELECT
      fsb.original_submission_id,
      fsb.form_version_id,
      fsb.user_id,
      fsb.created_at,
      fsb.completed_at,
      fsb.status,
      fsb.testmode,
      COUNT(DISTINCT ac.question_id) AS matched_question_count
    FROM filtered_submissions_base fsb
    LEFT JOIN answer_conditions ac ON fsb.original_submission_id = ac.submission_id
    GROUP BY
      fsb.original_submission_id, fsb.form_version_id, fsb.user_id, fsb.created_at, fsb.completed_at, fsb.status, fsb.testmode
  ),
  answer_filter_stats AS (
    -- Pre-calculates the total number of keys in answer_filters.
    SELECT
      CASE
        WHEN answer_filters IS NOT NULL AND answer_filters != '{}'::jsonb
        THEN (SELECT count(*) FROM jsonb_object_keys(answer_filters))::integer
        ELSE 0
      END AS total_filter_keys
  ),
  qualified_submissions AS (
    -- Selects submissions that pass all filters.
    SELECT
      smfc.original_submission_id,
      smfc.form_version_id,
      smfc.user_id,
      smfc.created_at,
      smfc.completed_at,
      smfc.status,
      smfc.testmode
    FROM submissions_meeting_filter_criteria smfc
    CROSS JOIN answer_filter_stats afs
    WHERE
      (
        afs.total_filter_keys = 0 OR
        smfc.matched_question_count = afs.total_filter_keys
      )
  ),
  aggregated_answers AS (
    -- Aggregates all answers for the qualified submissions.
    SELECT
      fa.submission_id,
      jsonb_object_agg(fa.question_id, fa.answer_value) as submission_answers
    FROM form_answers fa
    WHERE fa.submission_id IN (SELECT qs.original_submission_id FROM qualified_submissions qs)
    GROUP BY fa.submission_id
  ),
  paginated_results AS (
    -- Get paginated results with aggregated answers
    SELECT
      qs.original_submission_id::TEXT AS submission_id,
      qs.form_version_id::TEXT AS form_version_id,
      qs.user_id::TEXT AS user_id,
      qs.created_at,
      qs.completed_at,
      qs.last_updated_at,
      qs.status::TEXT AS status,
      qs.testmode,
      COALESCE(aa.submission_answers, '{}'::jsonb) AS answers,
      COALESCE(qs.sidecar, '{}'::jsonb) AS sidecar
    FROM qualified_submissions qs
    LEFT JOIN aggregated_answers aa ON qs.original_submission_id = aa.submission_id
    ORDER BY qs.created_at DESC
    LIMIT page_size OFFSET (page - 1) * page_size
  ),
  counts AS (
    -- Calculate counts from qualified submissions (filtered)
    SELECT
      COUNT(*) AS total_filtered,
      COUNT(*) FILTER (WHERE status = 'completed') AS completed,
      COUNT(*) FILTER (WHERE status = 'in_progress') AS in_progress
    FROM qualified_submissions
  ),
  total_counts AS (
    -- Calculate total counts for the form (ignoring all filters except form_version_id)
    SELECT
      COUNT(*) AS total,
      COUNT(*) FILTER (WHERE status = 'completed') AS total_completed,
      COUNT(*) FILTER (WHERE status = 'in_progress') AS total_in_progress
    FROM form_submissions
    WHERE form_version_id = (submission_filters->>'form_version_id')::uuid
  )
  -- Return a single row with data array and counts
  SELECT
    COALESCE(
      (SELECT jsonb_agg(row_to_json(pr.*)) FROM paginated_results pr),
      '[]'::jsonb
    ) AS data,
    tc.total AS total_count,
    tc.total_completed AS total_completed_count,
    tc.total_in_progress AS total_in_progress_count,
    c.total_filtered AS total_filtered_count,
    c.completed AS completed_count,
    c.in_progress AS in_progress_count
  FROM counts c
  CROSS JOIN total_counts tc;
END;
$$;


ALTER FUNCTION "public"."get_filtered_submissions"("submission_filters" "jsonb", "answer_filters" "jsonb", "page" integer, "page_size" integer) OWNER TO "postgres";
-- Pin search_path to empty string for security (lint 0011)
-- Keep search_path on 'public' for this function since it uses
-- unqualified table names (form_submissions) internally.
ALTER FUNCTION public.get_filtered_submissions(jsonb, jsonb, integer, integer) SET search_path = 'public';


CREATE OR REPLACE FUNCTION "public"."update_last_updated_at_column"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    -- Check if the operation is an UPDATE and the row data has actually changed
    IF TG_OP = 'UPDATE' AND OLD IS DISTINCT FROM NEW THEN
        NEW.last_updated_at = NOW();
    END IF;
    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."update_last_updated_at_column"() OWNER TO "postgres";
-- Pin search_path to empty string for security (lint 0011)
ALTER FUNCTION public.update_last_updated_at_column() SET search_path = '';


CREATE OR REPLACE FUNCTION "public"."update_submission_timestamp_on_answer"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
DECLARE
    target_submission_id UUID;
BEGIN
    IF (TG_OP = 'DELETE') THEN
        target_submission_id := OLD.submission_id;
    ELSE
        target_submission_id := NEW.submission_id;
    END IF;

    UPDATE public.form_submissions
    SET last_updated_at = NOW()
    WHERE submission_id = target_submission_id;

    IF (TG_OP = 'DELETE') THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END;
$$;


ALTER FUNCTION "public"."update_submission_timestamp_on_answer"() OWNER TO "postgres";
-- Pin search_path to empty string for security (lint 0011)
ALTER FUNCTION public.update_submission_timestamp_on_answer() SET search_path = '';


CREATE OR REPLACE FUNCTION "public"."update_updated_at_column"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    -- Check if the operation is an UPDATE and the row data has actually changed
    IF TG_OP = 'UPDATE' AND OLD IS DISTINCT FROM NEW THEN
        NEW.updated_at = NOW();
    END IF;
    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."update_updated_at_column"() OWNER TO "postgres";
-- Pin search_path to empty string for security (lint 0011)
ALTER FUNCTION public.update_updated_at_column() SET search_path = '';

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- Pin search_path to empty string for security (lint 0011)
ALTER FUNCTION public.set_updated_at() SET search_path = '';


CREATE OR REPLACE TRIGGER "check_anonymous_form_limit_trigger" BEFORE INSERT ON "public"."forms" FOR EACH ROW EXECUTE FUNCTION "public"."check_anonymous_form_limit"();



CREATE OR REPLACE TRIGGER "update_brands_updated_at" BEFORE UPDATE ON "public"."brands" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



CREATE OR REPLACE TRIGGER "update_form_versions_updated_at" BEFORE UPDATE ON "public"."form_versions" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



CREATE OR REPLACE TRIGGER "update_forms_updated_at" BEFORE UPDATE ON "public"."forms" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();

-- Enable RLS on tables with policies (lint 0007)
-- RLS enablement for these tables is deferred until full policy coverage is in place



CREATE OR REPLACE TRIGGER "update_submission_on_answer_change" AFTER INSERT OR DELETE OR UPDATE ON "public"."form_answers" FOR EACH ROW EXECUTE FUNCTION "public"."update_submission_timestamp_on_answer"();



CREATE OR REPLACE TRIGGER "update_submissions_last_updated_at" BEFORE UPDATE ON "public"."form_submissions" FOR EACH ROW EXECUTE FUNCTION "public"."update_last_updated_at_column"();

-- removed legacy actions_config trigger

ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "fk_auth_user" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."form_answers"
    ADD CONSTRAINT "fk_form_answers_submission" FOREIGN KEY ("submission_id") REFERENCES "public"."form_submissions"("submission_id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."form_submissions"
    ADD CONSTRAINT "fk_form_submissions_version" FOREIGN KEY ("form_version_id") REFERENCES "public"."form_versions"("version_id") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."form_versions"
    ADD CONSTRAINT "fk_form_versions_form" FOREIGN KEY ("form_id") REFERENCES "public"."forms"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."forms"
    ADD CONSTRAINT "fk_forms_brand" FOREIGN KEY ("brand_id") REFERENCES "public"."brands"("brand_id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."forms"
    ADD CONSTRAINT "current_draft_version_id" FOREIGN KEY ("current_draft_version_id") REFERENCES "public"."form_versions"("version_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."forms"
    ADD CONSTRAINT "current_published_version_id" FOREIGN KEY ("current_published_version_id") REFERENCES "public"."form_versions"("version_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;



ALTER TABLE ONLY "public"."form_chat_attachments"
    ADD CONSTRAINT "form_chat_attachments_form_id_fkey" FOREIGN KEY ("form_id") REFERENCES "public"."forms"("id");



ALTER TABLE ONLY "public"."form_versions"
    ADD CONSTRAINT "form_versions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."forms"
    ADD CONSTRAINT "forms_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."messages"
    ADD CONSTRAINT "messages_form_id_fkey" FOREIGN KEY ("form_id") REFERENCES "public"."forms"("id");



ALTER TABLE ONLY "public"."messages"
    ADD CONSTRAINT "messages_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."submission_chat_attachments"
    ADD CONSTRAINT "submission_chat_attachments_submission_id_fkey" FOREIGN KEY ("submission_id") REFERENCES "public"."form_submissions"("submission_id");



ALTER TABLE ONLY "public"."submission_messages"
    ADD CONSTRAINT "submission_messages_submission_id_fkey" FOREIGN KEY ("submission_id") REFERENCES "public"."form_submissions"("submission_id");



ALTER TABLE ONLY "public"."submission_messages"
    ADD CONSTRAINT "submission_messages_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."tasks"
    ADD CONSTRAINT "tasks_form_id_fkey" FOREIGN KEY ("form_id") REFERENCES "public"."forms"("id") ON DELETE CASCADE;

-- FK and index for forms.workspace_id (set null on workspace delete for safety)
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_type = 'FOREIGN KEY'
      AND table_schema = 'public'
      AND table_name = 'forms'
      AND constraint_name = 'forms_workspace_id_fkey'
  ) THEN
    ALTER TABLE ONLY "public"."forms"
      ADD CONSTRAINT "forms_workspace_id_fkey"
      FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces"("workspace_id") ON DELETE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes WHERE schemaname='public' AND tablename='forms' AND indexname='forms_workspace_id_idx'
  ) THEN
    CREATE INDEX "forms_workspace_id_idx" ON "public"."forms" USING btree ("workspace_id");
  END IF;
END $$;



ALTER TABLE ONLY "public"."usage_history"
    ADD CONSTRAINT "usage_history_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE CASCADE;

-- Enable RLS on tables with policies (lint 0007)
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.form_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.forms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workspaces ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;

-- Owner-scoped policies to cover SELECT/INSERT/UPDATE (delete policies already exist)
-- forms: rows owned by user_id
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='forms' AND policyname='forms_select_own'
  ) THEN
    CREATE POLICY "forms_select_own" ON public.forms
      FOR SELECT TO authenticated
      USING (user_id = auth.uid());
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='forms' AND policyname='forms_insert_own'
  ) THEN
    CREATE POLICY "forms_insert_own" ON public.forms
      FOR INSERT TO authenticated
      WITH CHECK (user_id = auth.uid());
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='forms' AND policyname='forms_update_own'
  ) THEN
    CREATE POLICY "forms_update_own" ON public.forms
      FOR UPDATE TO authenticated
      USING (user_id = auth.uid())
      WITH CHECK (user_id = auth.uid());
  END IF;
END $$;

-- brands: rows owned by created_by
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='brands' AND policyname='brands_select_own'
  ) THEN
    CREATE POLICY "brands_select_own" ON public.brands
      FOR SELECT TO authenticated
      USING (created_by = auth.uid());
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='brands' AND policyname='brands_insert_own'
  ) THEN
    CREATE POLICY "brands_insert_own" ON public.brands
      FOR INSERT TO authenticated
      WITH CHECK (created_by = auth.uid());
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='brands' AND policyname='brands_update_own'
  ) THEN
    CREATE POLICY "brands_update_own" ON public.brands
      FOR UPDATE TO authenticated
      USING (created_by = auth.uid())
      WITH CHECK (created_by = auth.uid());
  END IF;
END $$;

-- form_versions: rows owned through parent form
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='form_versions' AND policyname='form_versions_select_own'
  ) THEN
    CREATE POLICY "form_versions_select_own" ON public.form_versions
      FOR SELECT TO authenticated
      USING (EXISTS (
        SELECT 1 FROM public.forms f WHERE f.id = form_id AND f.user_id = auth.uid()
      ));
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='form_versions' AND policyname='form_versions_insert_own'
  ) THEN
    CREATE POLICY "form_versions_insert_own" ON public.form_versions
      FOR INSERT TO authenticated
      WITH CHECK (EXISTS (
        SELECT 1 FROM public.forms f WHERE f.id = form_id AND f.user_id = auth.uid()
      ));
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='form_versions' AND policyname='form_versions_update_own'
  ) THEN
    CREATE POLICY "form_versions_update_own" ON public.form_versions
      FOR UPDATE TO authenticated
      USING (EXISTS (
        SELECT 1 FROM public.forms f WHERE f.id = form_id AND f.user_id = auth.uid()
      ))
      WITH CHECK (EXISTS (
        SELECT 1 FROM public.forms f WHERE f.id = form_id AND f.user_id = auth.uid()
      ));
  END IF;
END $$;

-- workspaces: rows owned by created_by (owner-scoped; membership will come later)
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='workspaces' AND policyname='workspaces_select_own'
  ) THEN
    CREATE POLICY "workspaces_select_own" ON public.workspaces
      FOR SELECT TO authenticated
      USING (created_by = auth.uid());
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='workspaces' AND policyname='workspaces_insert_own'
  ) THEN
    CREATE POLICY "workspaces_insert_own" ON public.workspaces
      FOR INSERT TO authenticated
      WITH CHECK (created_by = auth.uid());
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='workspaces' AND policyname='workspaces_update_own'
  ) THEN
    CREATE POLICY "workspaces_update_own" ON public.workspaces
      FOR UPDATE TO authenticated
      USING (created_by = auth.uid())
      WITH CHECK (created_by = auth.uid());
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='workspaces' AND policyname='workspaces_delete_own'
  ) THEN
    CREATE POLICY "workspaces_delete_own" ON public.workspaces
      FOR DELETE TO authenticated
      USING (created_by = auth.uid());
  END IF;
END $$;

-- organizations: rows owned by created_by (owner-scoped for now)
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='organizations' AND policyname='organizations_select_own'
  ) THEN
    CREATE POLICY "organizations_select_own" ON public.organizations
      FOR SELECT TO authenticated
      USING (created_by = auth.uid());
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='organizations' AND policyname='organizations_insert_own'
  ) THEN
    CREATE POLICY "organizations_insert_own" ON public.organizations
      FOR INSERT TO authenticated
      WITH CHECK (created_by = auth.uid());
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='organizations' AND policyname='organizations_update_own'
  ) THEN
    CREATE POLICY "organizations_update_own" ON public.organizations
      FOR UPDATE TO authenticated
      USING (created_by = auth.uid())
      WITH CHECK (created_by = auth.uid());
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='organizations' AND policyname='organizations_delete_own'
  ) THEN
    CREATE POLICY "organizations_delete_own" ON public.organizations
      FOR DELETE TO authenticated
      USING (created_by = auth.uid());
  END IF;
END $$;


CREATE POLICY "Allow users to delete their own brands" ON "public"."brands" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "created_by"));



CREATE POLICY "Allow users to delete their own form versions" ON "public"."form_versions" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = ( SELECT "forms"."user_id" AS "created_by"
   FROM "public"."forms"
  WHERE ("forms"."id" = "form_versions"."form_id"))));



CREATE POLICY "Allow users to delete their own forms" ON "public"."forms" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));

-- Response Intelligence cache: small KV for AI summaries etc.
CREATE TABLE IF NOT EXISTS public.ri_ai_cache (
  id text PRIMARY KEY,
  value jsonb NOT NULL,
  meta jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Helper function: increment daily message count for a user
CREATE OR REPLACE FUNCTION public.increment_daily_message_count(user_id uuid)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE public.users
  SET daily_message_count = COALESCE(daily_message_count, 0) + 1
  WHERE id = increment_daily_message_count.user_id;
END;
$$;

-- Subscriptions: per-user subscription state (Polar/Billing)
CREATE TABLE IF NOT EXISTS "public"."user_subscriptions" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "user_id" uuid,
    "external_customer_id" text,
    "plan_type" text NOT NULL,
    "status" text NOT NULL,
    "current_period_end" timestamp with time zone,
    "created_at" timestamp with time zone,
    "updated_at" timestamp with time zone,
    CONSTRAINT "user_subscriptions_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "public"."user_subscriptions" OWNER TO "postgres";

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_type = 'FOREIGN KEY'
      AND table_schema = 'public'
      AND table_name = 'user_subscriptions'
      AND constraint_name = 'user_subscriptions_user_id_fkey'
  ) THEN
    ALTER TABLE ONLY "public"."user_subscriptions"
      ADD CONSTRAINT "user_subscriptions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE SET NULL;
  END IF;
END $$;

-- Subscription event log
CREATE TABLE IF NOT EXISTS "public"."subscription_logs" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "user_id" uuid,
    "action" text NOT NULL,
    "old_status" text,
    "new_status" text,
    "created_at" timestamp with time zone DEFAULT now(),
    CONSTRAINT "subscription_logs_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "public"."subscription_logs" OWNER TO "postgres";

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_type = 'FOREIGN KEY'
      AND table_schema = 'public'
      AND table_name = 'subscription_logs'
      AND constraint_name = 'subscription_logs_user_id_fkey'
  ) THEN
    ALTER TABLE ONLY "public"."subscription_logs"
      ADD CONSTRAINT "subscription_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");
  END IF;
END $$;
