#!/usr/bin/env bash
set -euo pipefail

# -----------------------------------------------------------------------------
# Supabase Env Sync (helper)
# -----------------------------------------------------------------------------
# Purpose:
# - Copy GOOGLE_CLIENT_ID/GOOGLE_CLIENT_SECRET from apps/formcraft/.env into the
#   canonical Supabase workdir (packages/db/supabase/.env) so humans can see a
#   single source of truth for local creds.
# - We also write GOTRUE_EXTERNAL_GOOGLE_ENABLED=true as a hint.
#
# Important:
# - The Supabase CLI v2 may NOT pass this .env into the GoTrue container.
#   Our main script (supabase-ensure_v1.sh) still exports these vars and, if the
#   provider is disabled, recreates the auth container with explicit env.
# - Treat this file as documentation and a convenience, not the single point of
#   truth. The recreation step is the reliable enforcement.
# -----------------------------------------------------------------------------

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$DIR/../../.." && pwd)"
APP_ENV="$ROOT/apps/formcraft/.env"
DB_ENV_DIR="$ROOT/packages/db/supabase"
DB_ENV="$DB_ENV_DIR/.env"

mkdir -p "$DB_ENV_DIR"

if [[ -f "$APP_ENV" ]]; then
  GOOGLE_CLIENT_ID=$(grep -E '^GOOGLE_CLIENT_ID=' "$APP_ENV" | tail -n1 || true)
  GOOGLE_CLIENT_SECRET=$(grep -E '^GOOGLE_CLIENT_SECRET=' "$APP_ENV" | tail -n1 || true)
  GOTRUE_ENABLED=$(grep -E '^GOTRUE_EXTERNAL_GOOGLE_ENABLED=' "$APP_ENV" | tail -n1 || true)
else
  GOOGLE_CLIENT_ID=""
  GOOGLE_CLIENT_SECRET=""
  GOTRUE_ENABLED=""
fi

# Build content
CONTENT="# Autogenerated by sync-supabase-env_v1.sh for local dev\n"
if [[ -n "$GOOGLE_CLIENT_ID" ]]; then CONTENT+="$GOOGLE_CLIENT_ID\n"; fi
if [[ -n "$GOOGLE_CLIENT_SECRET" ]]; then CONTENT+="$GOOGLE_CLIENT_SECRET\n"; fi
if [[ -z "$GOTRUE_ENABLED" ]]; then
  CONTENT+="GOTRUE_EXTERNAL_GOOGLE_ENABLED=true\n"
else
  CONTENT+="$GOTRUE_ENABLED\n"
fi

# Only write if we have at least client_id and secret
if [[ -n "$GOOGLE_CLIENT_ID" && -n "$GOOGLE_CLIENT_SECRET" ]]; then
  printf "%b" "$CONTENT" > "$DB_ENV"
  echo "[dev][env] Wrote Supabase env to $DB_ENV"
else
  echo "[dev][env] Missing GOOGLE_CLIENT_ID/GOOGLE_CLIENT_SECRET in apps/formcraft/.env; skipping sync."
fi
